## Basics ##

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

## Scans ##

# Timeout for starship to scan files (in milliseconds).
scan_timeout = 10000

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 10000

# Ignore global command_timeout setting and keep running external commands, no matter how long they take.
ignore_timeout = true

## Directory ##

[directory]
truncation_length = 3
truncate_to_repo = false
