#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Alacritty state=floating rectangle=800x600+750+1000
# bspc rule -a scratch sticky=on state=floating focus=on

# Auto Start 
# sxhkd & // Already ran at top of the script
picom --config "${HOME}"/.config/picom/picom.conf &
~/.fehbg &
dunst &
$HOME/.config/polybar/launch.sh &

# Create floating windows
alacritty --hold --class NF,NF -e bash -c "fastfetch; ~/Scripts/Terminal/color.sh; bash" & sleep 0.1 && bspc node --follow
alacritty --hold --class NF,NF -e bash -c "~/Scripts/Terminal/peaclock --config ~/.peaclock/config/default; bash" & sleep 0.1 && bspc node --follow
alacritty --hold --class NF,NF -e bash -c "~/Scripts/Terminal/pipes.sh; sudo ntpdate pool.ntp.org; bash" & sleep 0.1 && bspc node --follow
